# Generated by Django 4.1.5 on 2023-02-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shorturl',
            name='times_followed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
